"""Data Health page: data and concept drift monitoring for the RUL model."""

from typing import Any, Dict

import pandas as pd
import streamlit as st

from dashboard.components._theme import GLOBAL_CSS, metric_card, page_header
from dashboard.components.alerts import alert_banner
from dashboard.components.sidebar import render_sidebar
from monitoring.drift_report import demo_report


@st.cache_data(ttl=300)
def _load_report() -> Dict[str, Any]:
    """Build a drift report, cached for five minutes.

    Returns:
        The drift report dict from :func:`monitoring.drift_report.demo_report`.
    """
    return demo_report()


def render() -> None:
    """Render the full Data Health page."""
    st.set_page_config(page_title="Data Health", page_icon="🩺", layout="wide")
    st.markdown(GLOBAL_CSS, unsafe_allow_html=True)
    render_sidebar()
    st.markdown(
        page_header(
            "Data Health",
            "Feature and concept drift monitoring for the deployed model",
        ),
        unsafe_allow_html=True,
    )

    report = _load_report()
    summary = report["summary"]
    drift = bool(summary["drift_detected"])

    if drift:
        alert_banner(
            "Drift detected — the live sensor distribution has shifted "
            "from the training reference. Review the flagged features below.",
            "warning",
        )
    else:
        alert_banner("No significant drift — the model input is stable.", "success")

    cards = [
        (
            "Features Monitored",
            str(summary["n_features"]),
            "sensor channels",
            "#6366F1",
        ),
        (
            "KS-Drifted",
            str(len(summary["ks_drifted_features"])),
            "distribution shift",
            "#EF4444" if summary["ks_drifted_features"] else "#10B981",
        ),
        (
            "PSI-Significant",
            str(len(summary["psi_significant_features"])),
            "PSI > 0.2",
            "#EF4444" if summary["psi_significant_features"] else "#10B981",
        ),
        (
            "Concept Drift",
            "Yes" if summary["concept_drift_detected"] else "No",
            "prediction error",
            "#EF4444" if summary["concept_drift_detected"] else "#10B981",
        ),
    ]
    for col, (title, value, sub, color) in zip(st.columns(4), cards):
        with col:
            st.markdown(
                metric_card(title, value, sub, color), unsafe_allow_html=True
            )

    st.markdown("### Kolmogorov-Smirnov Test")
    st.caption("Per-feature distribution test; a feature drifts when p < 0.05.")
    ks_frame = pd.DataFrame(
        [
            {
                "Feature": name,
                "KS Statistic": round(result["statistic"], 4),
                "p-value": round(result["p_value"], 4),
                "Drifted": "🔴 Yes" if result["drifted"] else "🟢 No",
            }
            for name, result in report["ks_test"].items()
        ]
    )
    st.dataframe(ks_frame, use_container_width=True, hide_index=True)

    st.markdown("### Population Stability Index")
    st.caption("PSI < 0.1 stable · 0.1-0.2 moderate shift · > 0.2 significant.")
    psi_icons = {"none": "🟢", "moderate": "🟡", "significant": "🔴"}
    psi_frame = pd.DataFrame(
        [
            {
                "Feature": name,
                "PSI Score": round(result["psi_score"], 4),
                "Severity": f"{psi_icons.get(result['severity'], '')} "
                f"{result['severity'].title()}",
            }
            for name, result in report["psi"].items()
        ]
    )
    st.dataframe(psi_frame, use_container_width=True, hide_index=True)

    st.markdown("### Concept Drift")
    concept = report["concept_drift"]
    if concept["drift_detected"]:
        st.error(
            "Concept drift detected in the prediction-error stream at "
            f"change point index {concept['change_point']}. The relationship "
            "between sensor inputs and RUL has shifted — schedule a retrain."
        )
    else:
        st.success(
            "No concept drift — prediction-error behavior is stable over time."
        )

    st.caption(
        "Generated by monitoring/drift_report.py using the SentinelAI "
        "DriftDetector (KS · PSI · ADWIN-style concept drift)."
    )


render()
